receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:

exporters:
  debug:
  #    verbosity: detailed # detailed | normal | basic
  otlp:
    endpoint: jaeger-all-in-one:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [debug,otlp]

    metrics:
      receivers: [otlp]
      processors: []
      exporters: [debug]

    logs:
      receivers: [otlp]
      processors: []
      exporters: [debug]